### ISSUE TITLE
feat: Open Recents menu

### ISSUE THREAD

**Issue by democat3457** [xarkenz/mars-red#3]
An Open Recents dropdown menu option like how VSCode has it (under File > Open Recent) would be very helpful to reopen files from previous sessions.

**Comment by xarkenz** [comment]
That would be helpful, I agree. Though, I'm thinking--when should a file be added to the recents list, and when should a file be removed? My initial thought is to add a file to the list when its tab is closed, and remove it when it is opened. (And there would also be a limit on the number of files in the list, I assume. Maybe that limit could even be configurable.)

**Comment by democat3457** [comment]
I think the way VSCode does it is it adds to the list when a file is opened, and there's a "rolling window" of recents that it displays (i.e., FIFO with constant max size) which I think is the easiest implementation. 

The method you mentioned seems smarter (and more tailored to the use case), but it may be more complex to implement. Also, I think a configuration option for that max value might be on the verge of too much customization.

**Comment by xarkenz** [comment]
I could pretty easily implement it the VSCode way, then. And I'm not sure whether I agree with setting a maximum being too much customization, but regardless, what would be a good limit? 10 files?

**Comment by democat3457** [comment]
10 files is probably good

**Comment by xarkenz** [comment]
I finally got around to implementing this menu in the latest commit (https://github.com/xarkenz/mars-red/commit/c72a46d58e1230e16adbf54c308d950ee98a15d3). The limit is 10 files by default but is "configurable" in that it has a setting it draws from, though the user can't directly change it through the GUI. Let me know if you see any issues.
